@startuml

skinparam lineType ortho
skinparam classAttributeIconSize 0

class Roteiro {
    --
    + main(args: String[]): void
}

Roteiro --> TarefasController : utiliza como front controller
Roteiro --> Tarefa : instancia tarefas
Tarefa --> Prioridade : usa enum

@enduml
